// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * DifficultyDistribution
 */
export type DifficultyDistribution = {
    /**
     * Easy
     */
    easy?: number;
    /**
     * Medium
     */
    medium?: number;
    /**
     * Hard
     */
    hard?: number;
};

/**
 * GeneratedTopic
 */
export type GeneratedTopic = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Cognitive Levels
     */
    cognitive_levels: Array<string>;
    /**
     * Mcq Focus
     */
    mcq_focus: string;
    /**
     * Key Areas
     */
    key_areas: Array<string>;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * QuestionCreate
 */
export type QuestionCreate = {
    /**
     * Question
     */
    question: string;
    /**
     * Options
     */
    options: [
        string,
        string,
        string,
        string,
        string
    ];
    /**
     * Correct Option
     */
    correct_option: string;
    difficulty: QuestionDifficulty;
    /**
     * Cognitive Level
     */
    cognitive_level: string;
    /**
     * Explanation
     */
    explanation: string;
    /**
     * Topic Id
     */
    topic_id: string;
};

/**
 * QuestionDifficulty
 */
export type QuestionDifficulty = 'easy' | 'medium' | 'hard';

/**
 * QuestionGenerationRequest
 */
export type QuestionGenerationRequest = {
    /**
     * Topic Ids
     */
    topic_ids: Array<string>;
    difficulty_distribution?: DifficultyDistribution;
};

/**
 * QuestionPublic
 */
export type QuestionPublic = {
    /**
     * Question
     */
    question: string;
    /**
     * Options
     */
    options: [
        string,
        string,
        string,
        string,
        string
    ];
    /**
     * Correct Option
     */
    correct_option: string;
    difficulty: QuestionDifficulty;
    /**
     * Cognitive Level
     */
    cognitive_level: string;
    /**
     * Explanation
     */
    explanation: string;
    /**
     * Topic Id
     */
    topic_id: string;
    /**
     * Id
     */
    id: string;
    /**
     * Is Validated
     */
    is_validated: boolean;
    review_status: QuestionReviewStatus;
    /**
     * Created At
     */
    created_at?: unknown | null;
};

/**
 * QuestionReview
 */
export type QuestionReview = {
    review_status: QuestionReviewStatus;
};

/**
 * QuestionReviewStatus
 */
export type QuestionReviewStatus = 'pending' | 'approved' | 'rejected';

/**
 * QuestionUpdate
 */
export type QuestionUpdate = {
    /**
     * Question
     */
    question?: string | null;
    /**
     * Options
     */
    options?: [
        string,
        string,
        string,
        string,
        string
    ] | null;
    /**
     * Correct Option
     */
    correct_option?: string | null;
    difficulty?: QuestionDifficulty | null;
    /**
     * Cognitive Level
     */
    cognitive_level?: string | null;
    /**
     * Explanation
     */
    explanation?: string | null;
    /**
     * Topic Id
     */
    topic_id?: string | null;
};

/**
 * SubjectCreate
 */
export type SubjectCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Code
     */
    code?: string | null;
    /**
     * Clo
     */
    clo?: string | null;
};

/**
 * SubjectPublic
 */
export type SubjectPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Code
     */
    code?: string | null;
    /**
     * Clo
     */
    clo?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * SubjectUpdate
 */
export type SubjectUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Code
     */
    code?: string | null;
    /**
     * Clo
     */
    clo?: string | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * TopicBulkCreateRequest
 */
export type TopicBulkCreateRequest = {
    /**
     * Subject Id
     */
    subject_id: string;
    /**
     * Topics
     */
    topics: Array<GeneratedTopic>;
};

/**
 * TopicBulkCreateResponse
 */
export type TopicBulkCreateResponse = {
    /**
     * Topics
     */
    topics: Array<TopicPublic>;
};

/**
 * TopicCreate
 */
export type TopicCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Cognitive Levels
     */
    cognitive_levels: Array<string>;
    /**
     * Mcq Focus
     */
    mcq_focus: string;
    /**
     * Key Areas
     */
    key_areas: Array<string>;
    /**
     * Subject Id
     */
    subject_id: string;
};

/**
 * TopicGenerationRequest
 */
export type TopicGenerationRequest = {
    /**
     * Subject Id
     */
    subject_id: string;
    /**
     * Number Of Topics
     */
    number_of_topics?: number;
};

/**
 * TopicGenerationResponse
 */
export type TopicGenerationResponse = {
    /**
     * Topics
     */
    topics: Array<GeneratedTopic>;
};

/**
 * TopicPublic
 */
export type TopicPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Cognitive Levels
     */
    cognitive_levels: Array<string>;
    /**
     * Mcq Focus
     */
    mcq_focus: string;
    /**
     * Key Areas
     */
    key_areas: Array<string>;
    /**
     * Subject Id
     */
    subject_id: string;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * TopicUpdate
 */
export type TopicUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Cognitive Levels
     */
    cognitive_levels?: Array<string> | null;
    /**
     * Mcq Focus
     */
    mcq_focus?: string | null;
    /**
     * Key Areas
     */
    key_areas?: Array<string> | null;
    /**
     * Subject Id
     */
    subject_id?: string | null;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
    role?: UserRole;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    role: UserRole;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserRole
 */
export type UserRole = 'user' | 'editor';

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
    role?: UserRole | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type questionsReadQuestionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Topic Ids
         */
        topic_ids?: Array<string> | null;
    };
    url: '/api/v1/questions/';
};

export type questionsReadQuestionsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type questionsReadQuestionsError = questionsReadQuestionsErrors[keyof questionsReadQuestionsErrors];

export type questionsReadQuestionsResponses = {
    /**
     * Response Questions-Read Questions
     *
     * Successful Response
     */
    200: Array<QuestionPublic>;
};

export type questionsReadQuestionsResponse = questionsReadQuestionsResponses[keyof questionsReadQuestionsResponses];

export type questionsCreateQuestionData = {
    body: QuestionCreate;
    path?: never;
    query?: never;
    url: '/api/v1/questions/';
};

export type questionsCreateQuestionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type questionsCreateQuestionError = questionsCreateQuestionErrors[keyof questionsCreateQuestionErrors];

export type questionsCreateQuestionResponses = {
    /**
     * Successful Response
     */
    201: QuestionPublic;
};

export type questionsCreateQuestionResponse = questionsCreateQuestionResponses[keyof questionsCreateQuestionResponses];

export type questionsReadQuestionsForReviewData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Subject Id
         */
        subject_id?: string | null;
        /**
         * Topic Id
         */
        topic_id?: string | null;
    };
    url: '/api/v1/questions/review';
};

export type questionsReadQuestionsForReviewErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type questionsReadQuestionsForReviewError = questionsReadQuestionsForReviewErrors[keyof questionsReadQuestionsForReviewErrors];

export type questionsReadQuestionsForReviewResponses = {
    /**
     * Response Questions-Read Questions For Review
     *
     * Successful Response
     */
    200: Array<QuestionPublic>;
};

export type questionsReadQuestionsForReviewResponse = questionsReadQuestionsForReviewResponses[keyof questionsReadQuestionsForReviewResponses];

export type questionsDeleteQuestionData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/api/v1/questions/{question_id}';
};

export type questionsDeleteQuestionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type questionsDeleteQuestionError = questionsDeleteQuestionErrors[keyof questionsDeleteQuestionErrors];

export type questionsDeleteQuestionResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type questionsDeleteQuestionResponse = questionsDeleteQuestionResponses[keyof questionsDeleteQuestionResponses];

export type questionsReadQuestionData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/api/v1/questions/{question_id}';
};

export type questionsReadQuestionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type questionsReadQuestionError = questionsReadQuestionErrors[keyof questionsReadQuestionErrors];

export type questionsReadQuestionResponses = {
    /**
     * Successful Response
     */
    200: QuestionPublic;
};

export type questionsReadQuestionResponse = questionsReadQuestionResponses[keyof questionsReadQuestionResponses];

export type questionsUpdateQuestionData = {
    body: QuestionUpdate;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/api/v1/questions/{question_id}';
};

export type questionsUpdateQuestionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type questionsUpdateQuestionError = questionsUpdateQuestionErrors[keyof questionsUpdateQuestionErrors];

export type questionsUpdateQuestionResponses = {
    /**
     * Successful Response
     */
    200: QuestionPublic;
};

export type questionsUpdateQuestionResponse = questionsUpdateQuestionResponses[keyof questionsUpdateQuestionResponses];

export type questionsGenerateQuestionsData = {
    body: QuestionGenerationRequest;
    path?: never;
    query?: never;
    url: '/api/v1/questions/generate';
};

export type questionsGenerateQuestionsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type questionsGenerateQuestionsError = questionsGenerateQuestionsErrors[keyof questionsGenerateQuestionsErrors];

export type questionsGenerateQuestionsResponses = {
    /**
     * Response Questions-Generate Questions
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type questionsGenerateQuestionsResponse = questionsGenerateQuestionsResponses[keyof questionsGenerateQuestionsResponses];

export type questionsReviewQuestionData = {
    body: QuestionReview;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/api/v1/questions/{question_id}/review';
};

export type questionsReviewQuestionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type questionsReviewQuestionError = questionsReviewQuestionErrors[keyof questionsReviewQuestionErrors];

export type questionsReviewQuestionResponses = {
    /**
     * Successful Response
     */
    200: QuestionPublic;
};

export type questionsReviewQuestionResponse = questionsReviewQuestionResponses[keyof questionsReviewQuestionResponses];

export type subjectsReadSubjectsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/subjects/';
};

export type subjectsReadSubjectsResponses = {
    /**
     * Response Subjects-Read Subjects
     *
     * Successful Response
     */
    200: Array<SubjectPublic>;
};

export type subjectsReadSubjectsResponse = subjectsReadSubjectsResponses[keyof subjectsReadSubjectsResponses];

export type subjectsCreateSubjectData = {
    body: SubjectCreate;
    path?: never;
    query?: never;
    url: '/api/v1/subjects/';
};

export type subjectsCreateSubjectErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type subjectsCreateSubjectError = subjectsCreateSubjectErrors[keyof subjectsCreateSubjectErrors];

export type subjectsCreateSubjectResponses = {
    /**
     * Successful Response
     */
    201: SubjectPublic;
};

export type subjectsCreateSubjectResponse = subjectsCreateSubjectResponses[keyof subjectsCreateSubjectResponses];

export type subjectsDeleteSubjectData = {
    body?: never;
    path: {
        /**
         * Subject Id
         */
        subject_id: string;
    };
    query?: never;
    url: '/api/v1/subjects/{subject_id}';
};

export type subjectsDeleteSubjectErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type subjectsDeleteSubjectError = subjectsDeleteSubjectErrors[keyof subjectsDeleteSubjectErrors];

export type subjectsDeleteSubjectResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type subjectsDeleteSubjectResponse = subjectsDeleteSubjectResponses[keyof subjectsDeleteSubjectResponses];

export type subjectsReadSubjectData = {
    body?: never;
    path: {
        /**
         * Subject Id
         */
        subject_id: string;
    };
    query?: never;
    url: '/api/v1/subjects/{subject_id}';
};

export type subjectsReadSubjectErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type subjectsReadSubjectError = subjectsReadSubjectErrors[keyof subjectsReadSubjectErrors];

export type subjectsReadSubjectResponses = {
    /**
     * Successful Response
     */
    200: SubjectPublic;
};

export type subjectsReadSubjectResponse = subjectsReadSubjectResponses[keyof subjectsReadSubjectResponses];

export type subjectsUpdateSubjectData = {
    body: SubjectUpdate;
    path: {
        /**
         * Subject Id
         */
        subject_id: string;
    };
    query?: never;
    url: '/api/v1/subjects/{subject_id}';
};

export type subjectsUpdateSubjectErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type subjectsUpdateSubjectError = subjectsUpdateSubjectErrors[keyof subjectsUpdateSubjectErrors];

export type subjectsUpdateSubjectResponses = {
    /**
     * Successful Response
     */
    200: SubjectPublic;
};

export type subjectsUpdateSubjectResponse = subjectsUpdateSubjectResponses[keyof subjectsUpdateSubjectResponses];

export type topicsReadTopicsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Subject Id
         */
        subject_id?: string | null;
    };
    url: '/api/v1/topics/';
};

export type topicsReadTopicsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type topicsReadTopicsError = topicsReadTopicsErrors[keyof topicsReadTopicsErrors];

export type topicsReadTopicsResponses = {
    /**
     * Response Topics-Read Topics
     *
     * Successful Response
     */
    200: Array<TopicPublic>;
};

export type topicsReadTopicsResponse = topicsReadTopicsResponses[keyof topicsReadTopicsResponses];

export type topicsCreateTopicData = {
    body: TopicCreate;
    path?: never;
    query?: never;
    url: '/api/v1/topics/';
};

export type topicsCreateTopicErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type topicsCreateTopicError = topicsCreateTopicErrors[keyof topicsCreateTopicErrors];

export type topicsCreateTopicResponses = {
    /**
     * Successful Response
     */
    201: TopicPublic;
};

export type topicsCreateTopicResponse = topicsCreateTopicResponses[keyof topicsCreateTopicResponses];

export type topicsDeleteTopicData = {
    body?: never;
    path: {
        /**
         * Topic Id
         */
        topic_id: string;
    };
    query?: never;
    url: '/api/v1/topics/{topic_id}';
};

export type topicsDeleteTopicErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type topicsDeleteTopicError = topicsDeleteTopicErrors[keyof topicsDeleteTopicErrors];

export type topicsDeleteTopicResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type topicsDeleteTopicResponse = topicsDeleteTopicResponses[keyof topicsDeleteTopicResponses];

export type topicsReadTopicData = {
    body?: never;
    path: {
        /**
         * Topic Id
         */
        topic_id: string;
    };
    query?: never;
    url: '/api/v1/topics/{topic_id}';
};

export type topicsReadTopicErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type topicsReadTopicError = topicsReadTopicErrors[keyof topicsReadTopicErrors];

export type topicsReadTopicResponses = {
    /**
     * Successful Response
     */
    200: TopicPublic;
};

export type topicsReadTopicResponse = topicsReadTopicResponses[keyof topicsReadTopicResponses];

export type topicsUpdateTopicData = {
    body: TopicUpdate;
    path: {
        /**
         * Topic Id
         */
        topic_id: string;
    };
    query?: never;
    url: '/api/v1/topics/{topic_id}';
};

export type topicsUpdateTopicErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type topicsUpdateTopicError = topicsUpdateTopicErrors[keyof topicsUpdateTopicErrors];

export type topicsUpdateTopicResponses = {
    /**
     * Successful Response
     */
    200: TopicPublic;
};

export type topicsUpdateTopicResponse = topicsUpdateTopicResponses[keyof topicsUpdateTopicResponses];

export type topicsCreateTopicsData = {
    body: TopicBulkCreateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/topics/bulk';
};

export type topicsCreateTopicsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type topicsCreateTopicsError = topicsCreateTopicsErrors[keyof topicsCreateTopicsErrors];

export type topicsCreateTopicsResponses = {
    /**
     * Successful Response
     */
    201: TopicBulkCreateResponse;
};

export type topicsCreateTopicsResponse = topicsCreateTopicsResponses[keyof topicsCreateTopicsResponses];

export type topicsGenerateTopicsData = {
    body: TopicGenerationRequest;
    path?: never;
    query?: never;
    url: '/api/v1/topics/generate';
};

export type topicsGenerateTopicsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type topicsGenerateTopicsError = topicsGenerateTopicsErrors[keyof topicsGenerateTopicsErrors];

export type topicsGenerateTopicsResponses = {
    /**
     * Successful Response
     */
    200: TopicGenerationResponse;
};

export type topicsGenerateTopicsResponse = topicsGenerateTopicsResponses[keyof topicsGenerateTopicsResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];
