"""add user role

Revision ID: 972451aa7e59
Revises: fe56fa70289e
Create Date: 2026-08-30 17:27:17.302725

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "972451aa7e59"
down_revision = "fe56fa70289e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("item")
    user_role = sa.Enum(
        "user",
        "editor",
        name="userrole",
    )
    user_role.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "user",
        sa.Column(
            "role",
            user_role,
            nullable=False,
            server_default="user",
        ),
    )
    op.alter_column(
        "user",
        "role",
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "role")
    user_role = sa.Enum(
        "user",
        "editor",
        name="userrole",
    )
    user_role.drop(op.get_bind(), checkfirst=True)
    op.create_table(
        "item",
        sa.Column(
            "description", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("title", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("owner_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
            name=op.f("item_owner_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("item_pkey")),
    )
    # ### end Alembic commands ###


#
