"""add topic and question tables

Revision ID: f834c30be2b2
Revises: bc761fab2824
Create Date: 2026-08-30 19:27:24.912937

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f834c30be2b2'
down_revision = 'bc761fab2824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cognitive_levels', sa.JSON(), nullable=False),
    sa.Column('mcq_focus', sa.Text(), nullable=False),
    sa.Column('key_areas', sa.JSON(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_subject_id'), 'topic', ['subject_id'], unique=False)
    op.create_table('question',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_option', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='questiondifficulty'), nullable=False),
    sa.Column('cognitive_level', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='questionreviewstatus'), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_topic_id'), 'question', ['topic_id'], unique=False)
    op.create_index(op.f('ix_subject_name'), 'subject', ['name'], unique=True)
    op.create_unique_constraint(None, 'subject', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject', type_='unique')
    op.drop_index(op.f('ix_subject_name'), table_name='subject')
    op.drop_index(op.f('ix_question_topic_id'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_topic_subject_id'), table_name='topic')
    op.drop_table('topic')
    # ### end Alembic commands ###
