/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutSubjectsRouteImport } from './routes/_layout/subjects'
import { Route as LayoutTopicsRouteImport } from './routes/_layout/topics'
import { Route as LayoutQuestionsIndexRouteImport } from './routes/_layout/questions/index'
import { Route as LayoutQuestionsReviewRouteImport } from './routes/_layout/questions/review'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSubjectsRoute = LayoutSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTopicsRoute = LayoutTopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQuestionsIndexRoute = LayoutQuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQuestionsReviewRoute = LayoutQuestionsReviewRouteImport.update({
  id: '/questions/review',
  path: '/questions/review',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/settings': typeof LayoutSettingsRoute
  '/subjects': typeof LayoutSubjectsRoute
  '/topics': typeof LayoutTopicsRoute
  '/questions/review': typeof LayoutQuestionsReviewRoute
  '/questions/': typeof LayoutQuestionsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/settings': typeof LayoutSettingsRoute
  '/subjects': typeof LayoutSubjectsRoute
  '/topics': typeof LayoutTopicsRoute
  '/': typeof LayoutIndexRoute
  '/questions/review': typeof LayoutQuestionsReviewRoute
  '/questions': typeof LayoutQuestionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/subjects': typeof LayoutSubjectsRoute
  '/_layout/topics': typeof LayoutTopicsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/questions/review': typeof LayoutQuestionsReviewRoute
  '/_layout/questions/': typeof LayoutQuestionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/settings'
    | '/subjects'
    | '/topics'
    | '/questions/review'
    | '/questions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/settings'
    | '/subjects'
    | '/topics'
    | '/'
    | '/questions/review'
    | '/questions'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/settings'
    | '/_layout/subjects'
    | '/_layout/topics'
    | '/_layout/'
    | '/_layout/questions/review'
    | '/_layout/questions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/subjects': {
      id: '/_layout/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof LayoutSubjectsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/topics': {
      id: '/_layout/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof LayoutTopicsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/questions/': {
      id: '/_layout/questions/'
      path: '/questions'
      fullPath: '/questions/'
      preLoaderRoute: typeof LayoutQuestionsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/questions/review': {
      id: '/_layout/questions/review'
      path: '/questions/review'
      fullPath: '/questions/review'
      preLoaderRoute: typeof LayoutQuestionsReviewRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSubjectsRoute: typeof LayoutSubjectsRoute
  LayoutTopicsRoute: typeof LayoutTopicsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutQuestionsReviewRoute: typeof LayoutQuestionsReviewRoute
  LayoutQuestionsIndexRoute: typeof LayoutQuestionsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSubjectsRoute: LayoutSubjectsRoute,
  LayoutTopicsRoute: LayoutTopicsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutQuestionsReviewRoute: LayoutQuestionsReviewRoute,
  LayoutQuestionsIndexRoute: LayoutQuestionsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
